### ISSUE TITLE
Configure Error in High Resolution ADC Channel

### ISSUE THREAD

**Issue by spusuluri** [spusuluri/bme590_lab8_code#2]
https://github.com/spusuluri/bme590_lab8_code/blob/e5798812a9f34edda0bf607e7631a425981f8c66/src/main.c#L260

It gives me the following error when I flash the code to the board: 

[00:00:00.344,085] <err> adc_nrfx_saadc: Selected ADC reference is not valid
[00:00:00.344,085] <err> Lab8_Satya: Could not setup Res High ADC channel (-22)
[00:00:00.344,116] <err> Lab8_Satya: Error configuring IO pins (err = -22)

I was thinking that it had to do with the overlay but not completely sure.

**Comment by mlp6** [comment]
It seems to be working fine for me (latest commit in `main`); but only reading one ADC channel?

```
[00:00:42.314,636] <dbg> Lab8_Satya: read_adc: Raw ADC Buffer: 14
[00:00:42.314,636] <inf> Lab8_Satya: ADC Value (mV): 164
[00:00:43.306,854] <dbg> Lab8_Satya: heartbeat_toggle: Heartbeat
[00:00:43.314,758] <inf> Lab8_Satya: Measuring adc@40007000 (channel 0)...
[00:00:43.314,819] <dbg> Lab8_Satya: read_adc: Raw ADC Buffer: 14
[00:00:43.314,819] <inf> Lab8_Satya: ADC Value (mV): 164
[00:00:44.306,854] <dbg> Lab8_Satya: heartbeat_toggle: Heartbeat
```

**Comment by mlp6** [comment]
Ah, I switched the ADC line in your code and see the error now...

**Comment by mlp6** [comment]
Fixed if you add the following line to `prf.conf`:
```
CONFIG_ADC_NRFX_SAADC=y
```

**Comment by spusuluri** [comment]
I added that line to the project configuration file but I still get the same Logging Error for the second ADC channel setup code.

**Comment by mlp6** [comment]
Did you do a pristine build?

**Comment by spusuluri** [comment]
I did. Still getting this error.
```
*** Booting Zephyr OS build v3.2.99-ncs1 ***
[00:00:00.315,917] <err> adc_nrfx_saadc: Selected ADC reference is not valid
[00:00:00.315,917] <err> Lab8_Satya: Could not setup Res High ADC channel (-22)
[00:00:00.315,948] <err> Lab8_Satya: Error configuring IO pins (err = -22)
```

**Comment by mlp6** [comment]
![image](https://user-images.githubusercontent.com/3239175/226217200-6ae28b19-6732-4a97-9162-204d42972829.png)

**Comment by mlp6** [comment]
Looks like only `VDD/4` can be used on this specific chip.

**Comment by spusuluri** [comment]
Error is fixed.
